import { keyBy } from 'lodash-es';
import { GetSmartDeviceModelDpSchema } from '@ray-js/panel-sdk';

export const lampSchema = [
  {
    attr: 641,
    canTrigger: true,
    code: 'switch_led',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power',
    id: 20,
    mode: 'rw',
    name: 'Switch',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'work_mode',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 21,
    mode: 'rw',
    name: 'Mode',
    property: {
      range: ['white', 'colour', 'scene', 'music'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'bright_value',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-liangdu1',
    id: 22,
    mode: 'rw',
    name: 'Brightness Value',
    property: {
      min: 10,
      max: 1000,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'temp_value',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_half',
    id: 23,
    mode: 'rw',
    name: 'Temperature Value',
    property: {
      min: 0,
      max: 1000,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 512,
    canTrigger: true,
    code: 'colour_data',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 24,
    mode: 'rw',
    name: 'Color Light',
    property: {
      type: 'string',
      maxlen: 255,
    },
    type: 'obj',
  },
  {
    attr: 512,
    canTrigger: true,
    code: 'scene_data',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 25,
    mode: 'rw',
    name: 'Scene',
    property: {
      type: 'string',
      maxlen: 255,
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'countdown',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-a_nav_timer',
    id: 26,
    mode: 'rw',
    name: 'Countdown Remaining Time',
    property: {
      unit: 's',
      min: 0,
      max: 86400,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 128,
    canTrigger: true,
    code: 'music_data',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mic',
    id: 27,
    mode: 'wr',
    name: 'Music Light',
    property: {
      type: 'string',
      maxlen: 255,
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'control_data',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_box2',
    id: 28,
    mode: 'wr',
    name: 'Control',
    property: {
      type: 'string',
      maxlen: 255,
    },
    type: 'obj',
  },
  {
    attr: 128,
    canTrigger: true,
    code: 'debug_data',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_tool',
    id: 29,
    mode: 'rw',
    name: 'Debug',
    property: {
      type: 'string',
      maxlen: 255,
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'rhythm_mode',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_time3',
    id: 30,
    mode: 'rw',
    name: 'Circadian Rhythm',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'sleep_mode',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_sleep',
    id: 31,
    mode: 'rw',
    name: 'Sleep Mode',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'wakeup_mode',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_sun',
    id: 32,
    mode: 'rw',
    name: 'Wake Up',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'power_memory',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_lightning',
    id: 33,
    mode: 'rw',
    name: 'Power Memory',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'do_not_disturb',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_sleep',
    id: 34,
    mode: 'rw',
    name: 'Do Not Disturb',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'switch_gradient',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 35,
    mode: 'rw',
    name: 'Switch Gradient',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
  {
    attr: 512,
    canTrigger: true,
    code: 'white_gradi_time',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_light',
    id: 48,
    mode: 'rw',
    name: 'White Light Gradient Time',
    property: {
      unit: 'ms',
      min: 0,
      max: 10000,
      scale: 0,
      step: 200,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 512,
    canTrigger: true,
    code: 'colour_gradi_time',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_shield',
    id: 49,
    mode: 'rw',
    name: 'Color Light Gradient Time',
    property: {
      unit: 'ms',
      min: 0,
      max: 10000,
      scale: 0,
      step: 200,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 96,
    canTrigger: false,
    code: 'remote_switch',
    defaultRecommend: false,
    editPermission: false,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_power2',
    id: 41,
    mode: 'rw',
    name: 'Wi-Fi Remote Control Switch',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'candle_mode_data',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-huoyan',
    id: 82,
    mode: 'rw',
    name: 'Candle Light Simulation',
    property: {
      type: 'raw',
      maxlen: 128,
    },
    type: 'raw',
  },
  {
    attr: 128,
    canTrigger: true,
    code: 'cycle_timing',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_time',
    id: 209,
    mode: 'rw',
    name: 'Cycle Timing',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  {
    attr: 128,
    canTrigger: true,
    code: 'random_timing',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_time3',
    id: 210,
    mode: 'rw',
    name: 'Random Timing',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'dreamlight_scene_mode',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_time3',
    id: 210,
    mode: 'rw',
    name: 'Dream Light Scene',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  // Custom DPs added for Device Selector and Shabbat Clock
  {
    code: 'selected_device',
    id: 101,
    mode: 'rw',
    name: 'Selected Device',
    type: 'obj',
    property: {
      type: 'enum',
      range: ['Device1', 'Device2', 'Device3'],
    },
  },
  {
    code: 'dev_name_1',
    id: 102,
    mode: 'rw',
    name: 'Device Name 1',
    type: 'obj',
    property: { type: 'string' },
  },
  {
    code: 'dev_name_2',
    id: 103,
    mode: 'rw',
    name: 'Device Name 2',
    type: 'obj',
    property: { type: 'string' },
  },
  {
    code: 'dev_name_3',
    id: 104,
    mode: 'rw',
    name: 'Device Name 3',
    type: 'obj',
    property: { type: 'string' },
  },
  {
    code: 'shabat_clock',
    id: 105,
    mode: 'rw',
    name: 'Shabbat Clock',
    type: 'obj',
    property: { type: 'bool' },
  },
  {
    code: 'shabat_entry_hour',
    id: 106,
    mode: 'rw',
    name: 'Shabbat Entry Hour',
    type: 'obj',
    property: { type: 'value', min: 0, max: 23 },
  },
  {
    code: 'shabat_entry_minute',
    id: 107,
    mode: 'rw',
    name: 'Shabbat Entry Minute',
    type: 'obj',
    property: { type: 'value', min: 0, max: 59 },
  },
  {
    code: 'shabat_exit_hour',
    id: 108,
    mode: 'rw',
    name: 'Shabbat Exit Hour',
    type: 'obj',
    property: { type: 'value', min: 0, max: 23 },
  },
  {
    code: 'shabat_exit_minute',
    id: 109,
    mode: 'rw',
    name: 'Shabbat Exit Minute',
    type: 'obj',
    property: { type: 'value', min: 0, max: 59 },
  },
] as const;

export const lampSchemaMap = keyBy(lampSchema, 'code') as GetSmartDeviceModelDpSchema<
  typeof lampSchema
>;
