import { keyBy } from 'lodash-es';
import { GetSmartDeviceModelDpSchema } from '@ray-js/panel-sdk';

export const lampSchema = [
  {
    attr: 641,
    canTrigger: true,
    code: 'switch_led',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power',
    id: 20,
    mode: 'rw',
    name: 'Switch',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'work_mode',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 21,
    mode: 'rw',
    name: 'Mode',
    property: {
      range: ['white', 'colour', 'scene', 'music'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'bright_value',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-liangdu1',
    id: 22,
    mode: 'rw',
    name: 'Brightness Value',
    property: {
      min: 10,
      max: 1000,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'temp_value',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_half',
    id: 23,
    mode: 'rw',
    name: 'Temperature Value',
    property: {
      min: 0,
      max: 1000,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 512,
    canTrigger: true,
    code: 'colour_data',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 24,
    mode: 'rw',
    name: 'Color Light',
    property: {
      type: 'string',
      maxlen: 255,
    },
    type: 'obj',
  },
  {
    attr: 512,
    canTrigger: true,
    code: 'scene_data',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 25,
    mode: 'rw',
    name: 'Scene',
    property: {
      type: 'string',
      maxlen: 255,
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'countdown',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-a_nav_timer',
    id: 26,
    mode: 'rw',
    name: 'Countdown Remaining Time',
    property: {
      unit: 's',
      min: 0,
      max: 86400,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 128,
    canTrigger: true,
    code: 'music_data',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mic',
    id: 27,
    mode: 'wr',
    name: 'Music Light',
    property: {
      type: 'string',
      maxlen: 255,
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'control_data',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_box2',
    id: 28,
    mode: 'wr',
    name: 'Control',
    property: {
      type: 'string',
      maxlen: 255,
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'sleep_mode',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_sleep',
    id: 31,
    mode: 'rw',
    name: 'Sleep Mode',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'wakeup_mode',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_sun',
    id: 32,
    mode: 'rw',
    name: 'Wake Up',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'power_memory',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_lightning',
    id: 33,
    mode: 'rw',
    name: 'Power Memory',
    property: {
      type: 'raw',
      maxlen: 255,
    },
    type: 'raw',
  },
  // Product Custom & Extended DPs
  {
    code: 'DIMMER_SN',
    id: 101,
    mode: 'ro',
    name: 'Dimmer Serial',
    type: 'obj',
    property: { type: 'string' },
  },
  {
    code: 'set_pairing_device',
    id: 102,
    mode: 'wr',
    name: 'Set Pairing Device',
    type: 'obj',
    property: { type: 'bool' },
  },
  {
    code: 'temperature',
    id: 103,
    mode: 'ro',
    name: 'Internal Temperature',
    type: 'obj',
    property: { type: 'value', min: 0, max: 200, unit: '°C' },
  },
  {
    code: 'dim_speed',
    id: 104,
    mode: 'rw',
    name: 'Dimming Speed',
    type: 'obj',
    property: { type: 'value', min: 5, max: 160 },
  },
  {
    code: 'button_light',
    id: 105,
    mode: 'rw',
    name: 'Button Light Enable',
    type: 'obj',
    property: { type: 'bool' },
  },
  {
    code: 'set_remote_button',
    id: 106,
    mode: 'wr',
    name: 'Assign Remote Button',
    type: 'obj',
    property: { type: 'bool' },
  },
  {
    code: 'dimming_speed', // Dimming Start Point in list
    id: 107,
    mode: 'rw',
    name: 'Dimming Start Point',
    type: 'obj',
    property: { type: 'value', min: 0, max: 100, unit: '%' },
  },
  {
    code: 'selected_device',
    id: 108,
    mode: 'rw',
    name: 'Selected Device',
    type: 'obj',
    property: {
      type: 'enum',
      range: ['Device1', 'Device2', 'Device3'],
    },
  },
  {
    code: 'min_dim_level',
    id: 109,
    mode: 'rw',
    name: 'Minimum Dim Level',
    type: 'obj',
    property: { type: 'value', min: 0, max: 60, unit: '%' },
  },
  {
    code: 'firmware_version',
    id: 110,
    mode: 'ro',
    name: 'Firmware Version',
    type: 'obj',
    property: { type: 'string' },
  },
  {
    code: 'dev_name_1',
    id: 111,
    mode: 'rw',
    name: 'Device Name 1',
    type: 'obj',
    property: { type: 'string' },
  },
  {
    code: 'dev_name_2',
    id: 112,
    mode: 'rw',
    name: 'Device Name 2',
    type: 'obj',
    property: { type: 'string' },
  },
  {
    code: 'dev_name_3',
    id: 113,
    mode: 'rw',
    name: 'Device Name 3',
    type: 'obj',
    property: { type: 'string' },
  },
  {
    code: 'shabat_entry_hour',
    id: 114,
    mode: 'rw',
    name: 'Shabbat Entry Hour',
    type: 'obj',
    property: { type: 'value', min: 0, max: 23 },
  },
  {
    code: 'shabat_entry_min',
    id: 115,
    mode: 'rw',
    name: 'Shabbat Entry Minute',
    type: 'obj',
    property: { type: 'value', min: 0, max: 59 },
  },
  {
    code: 'shabat_exit_hour',
    id: 116,
    mode: 'rw',
    name: 'Shabbat Exit Hour',
    type: 'obj',
    property: { type: 'value', min: 0, max: 23 },
  },
  {
    code: 'shabat_exit_min',
    id: 117,
    mode: 'rw',
    name: 'Shabbat Exit Minute',
    type: 'obj',
    property: { type: 'value', min: 0, max: 59 },
  },
  // Shabbat Scenes 0-5
  { code: 'sbabat_scn0_h', id: 118, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 25 } },
  { code: 'shabat_scn0_m', id: 119, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 59 } },
  { code: 'shabat_scn1_h', id: 120, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 23 } },
  { code: 'shabat_scn1_m', id: 121, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 59 } },
  { code: 'shabat_scn2_h', id: 122, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 23 } },
  { code: 'shabat_scn2_m', id: 123, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 59 } },
  { code: 'shabat_scn3_h', id: 124, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 23 } },
  { code: 'shabat_scn3_m', id: 125, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 59 } },
  { code: 'shabat_scn4_h', id: 126, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 23 } },
  { code: 'shabat_scn4_m', id: 127, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 59 } },
  { code: 'shabat_scn5_h', id: 128, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 23 } },
  { code: 'shabat_scn5_m', id: 129, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 59 } },
  { code: 'cycle_time', id: 130, mode: 'rw', type: 'obj', property: { type: 'string' } },
  { code: 'scenario_text', id: 131, mode: 'rw', type: 'obj', property: { type: 'string' } },
  { code: 'a_test', id: 132, mode: 'rw', type: 'raw', property: { type: 'raw' } },
  {
    code: 'sp',
    id: 133,
    mode: 'rw',
    name: 'Lamp Type',
    type: 'obj',
    property: {
      type: 'enum',
      range: [
        '0_None',
        '1_Start',
        '2_End',
        '3_Mid1',
        '4_Mid2',
        '5_End1',
        '6_End2',
        '7_End3',
        '8_On_Off',
        '9_Mid_Reverse',
      ],
    },
  },
  { code: 'shabat_scn0_level', id: 144, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 100 } },
  { code: 'shabat_scn1_level', id: 145, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 100 } },
  { code: 'shabat_scn2_level', id: 146, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 100 } },
  { code: 'shabat_scn3_level', id: 147, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 100 } },
  { code: 'shabat_scn4_level', id: 148, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 100 } },
  { code: 'shabat_scn5_level', id: 149, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 100 } },
  { code: 'save_shabat_data', id: 150, mode: 'rw', type: 'obj', property: { type: 'bool' } },
  { code: 'shabat_clock', id: 151, mode: 'rw', type: 'obj', property: { type: 'bool' } },
  { code: 'test_timer', id: 152, mode: 'rw', type: 'obj', property: { type: 'bool' } },
  { code: 'year', id: 153, mode: 'rw', type: 'obj', property: { type: 'value', min: 2024, max: 2034 } },
  { code: 'month', id: 154, mode: 'rw', type: 'obj', property: { type: 'value', min: 1, max: 12 } },
  { code: 'day', id: 155, mode: 'rw', type: 'obj', property: { type: 'value', min: 1, max: 31 } },
  {
    code: 'weekday',
    id: 156,
    mode: 'rw',
    type: 'obj',
    property: {
      type: 'enum',
      range: ['Sunday', 'Moneday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Suterday'],
    },
  },
  { code: 'hour', id: 157, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 23 } },
  { code: 'minute', id: 158, mode: 'rw', type: 'obj', property: { type: 'value', min: 0, max: 59 } },
  { code: 'active_scenario', id: 159, mode: 'ro', type: 'obj', property: { type: 'value', min: 0, max: 7 } },
  { code: 'shabat_test_on', id: 160, mode: 'rw', type: 'obj', property: { type: 'bool' } },
  {
    code: 'set_max_dimming',
    id: 161,
    mode: 'rw',
    name: 'Maximum Dim Level',
    type: 'obj',
    property: { type: 'value', min: 10, max: 100, unit: '%' },
  },
  {
    code: 'weekend_day',
    id: 162,
    mode: 'rw',
    name: 'Weekend Day',
    type: 'obj',
    property: { type: 'enum', range: ['Friday', 'Saturday'] },
  },
  { code: 'scn_ord_err', id: 163, mode: 'ro', type: 'obj', property: { type: 'bool' } },
  {
    code: 'DT',
    id: 164,
    mode: 'ro',
    name: 'Dimmer Type',
    type: 'obj',
    property: { type: 'enum', range: ['NNN', 'NND', 'NDN', 'DNN', 'NDD', 'DND', 'DDN', 'DDD'] },
  },
  { code: 'update_time', id: 165, mode: 'wr', type: 'obj', property: { type: 'bool' } },
  { code: 'dhabat_scn1_fixed', id: 166, mode: 'rw', type: 'obj', property: { type: 'bool' } },
  { code: 'shabat_scn2_fixed', id: 167, mode: 'rw', type: 'obj', property: { type: 'bool' } },
  { code: 'shabat_scn3_fixed', id: 168, mode: 'rw', type: 'obj', property: { type: 'bool' } },
  { code: 'shabat_scn4_fixed', id: 169, mode: 'rw', type: 'obj', property: { type: 'bool' } },
  { code: 'shabat_scn5_fixed', id: 170, mode: 'rw', type: 'obj', property: { type: 'bool' } },
  { code: 'shabat_scn6_fixed', id: 171, mode: 'rw', type: 'obj', property: { type: 'bool' } },
  { code: 'clear_pairing', id: 172, mode: 'wr', type: 'obj', property: { type: 'bool' } },
] as const;

export const lampSchemaMap = keyBy(lampSchema, 'code') as GetSmartDeviceModelDpSchema<
  typeof lampSchema
>;
